spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:younglog
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true

  sql:
    init:
      mode: always

  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp